### ISSUE TITLE
bug of  Recv 

### ISSUE THREAD

**Issue by qqwx1986** [leenjewel/node-kcp#1]
NAN_METHOD(KCPObject::Recv)
    {
        KCPObject* thiz = ObjectWrap::Unwrap<KCPObject>(info.Holder());
        int bufsize = 0;
        char* buf = NULL;
        int buflen = 0;
        char* data = NULL;
        int len = 0;
        char* tmp = NULL;
        int tmplen = 0;
        while(1) {
            tmplen = len;//chg one（修改1）
            bufsize = ikcp_peeksize(thiz->kcp);
            if (bufsize <= 0) {
                break;
            }
            int align = bufsize % 4;
            if (align) {
                bufsize += 4 - align;
            }
            buf = (char*)malloc(bufsize);
            buflen = ikcp_recv(thiz->kcp, buf, bufsize);
            if (buflen <= 0) {
                free(buf);
                break;
            }
            len += buflen;
            tmp = data;
            data = (char*)malloc(len);
            if (NULL != tmp) {
                memcpy(data, tmp, tmplen);
                free(tmp);
            }
            memcpy(data+tmplen, buf, buflen); //chg 2, copy need offset（修改2，开始没有偏移量，所以每次都拷贝在offset 0）
            free(buf);
        }
        if (len > 0) {
            info.GetReturnValue().Set(
                Nan::CopyBuffer((const char*)data, len).ToLocalChecked()
            );
        }
        free(data);
    }

**Comment by leenjewel** [comment]
THX! I have fixed it and commit
