### ISSUE TITLE
KcpObject::Recv实现似乎有误

### ISSUE THREAD

**Issue by zsxsoft** [leenjewel/node-kcp#5]
https://github.com/leenjewel/node-kcp/blob/master/src/kcpobject.cc#L195
此处代码，似乎使用流的方式调用了`ikcp_recv`。但KCP的默认工作模式是包模式，不应该进行拼接：https://github.com/skywind3000/kcp/issues/238

**Comment by Jarvan-via** [comment]
兄弟  你能提一手pr 吗，我也遇到这个问题了

**Comment by leenjewel** [comment]
https://github.com/leenjewel/node-kcp/blob/master/src/kcpobject.cc#L200

那个 while 循环最后直接 break 一下看看是否能解决问题。如果包模式不需要拼接，那么 while 走一遍直接 break 就应该解决问题，试试看

**Comment by Jarvan-via** [comment]
@leenjewel  兄弟 我加了break 重新编译之后 问题解决了 thanks

**Comment by leenjewel** [comment]
OK，我这边也发布一下新版本 v1.0.12 默认是包模式，也支持 stream 模式

**Comment by Jarvan-via** [comment]
@leenjewel  妙啊 兄弟
